title: ECE Wellness
description: (Student run) ECE Wellness resources page for Spring 2024.
theme: just-the-docs

url: https://ecewellness.ca

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
